

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: 123

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/my-realm